inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  NewCops: disable
  Include:
    - lib/**/*.rb
    - spec/**/*.rb

Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
