name: Rubocop Check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  rubocop:
      name: Rubocop
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: prozsolt/rubocop-github-action@master
